export enum PermissionType {
  AssignTrainingToSelf = 1,
  AssignTrainings,
  EditOwnProfile,
    AddCoaches,
  ManageCoaches,
  AddHalls,
  ManageHalls,
  AddTrainings,
  ManageTrainings,
  AddClients,
  ManageClients,
  AddManagers,
  ManageManagers,
}
